### ISSUE TITLE
Seeking some advices~

### ISSUE THREAD

**Issue by youyuge34** [lartpang/Segmentation-Saliency-Dataset#10]
It is a fantastic project within saliency domaina and I got lots of inspiration from it. In this domain I am a newbie and I am seeking some professional advices~ I am sorry that I wrote down the following consults in the issues block due to that I cannot find your e-mail address on your page.         
      

**Here is the background of my problem:**      
In most cases when cropping images, we just crop the center part of the whole image to get the disired size or ratio, which is far from perfect. I am thinking about some content-aware based cropping methods like salient detection or image retargetting. I found that image retargetting may cause Image distortion artifacts in some cases which is not stable enough. Maybe salient detection method is a good way to detect the main object in the image first and then we can crop it out in a fixed size ratio. 
- Any advice from you? 
- Maybe u can recommend some fast and stable algorithm in the domain of salient detection？
- Or, there are some better ways to handle with it?

THX~

**Comment by lartpang** [comment]
@youyuge34 I am sorry to see your issue so late.

The problem you said does make a lot of sense. As far as I know, some work uses some saliency method to adjust the shape of the image and preserve the shape of the original important target as much as possible. But I can't remember a bit, I need to check some information.

I will reply about it later, of course, you can also check out some reviews or surveys about saliency detection.

**Comment by lartpang** [comment]
I find some thing in `Salient Object Detection in the Deep Learning Era: An In-Depth Survey`:

![image](https://user-images.githubusercontent.com/26847524/61060774-a9c11e00-a42d-11e9-9da7-218058123b00.png)

* [17] W. Wang, J. Shen, and H. Ling, “A deep network solution for attention and aesthetics aware photo cropping,” IEEE Trans. Pattern Anal. Mach. Intell., 2018.
* [18] S. Avidan and A. Shamir, “Seam carving for content-aware image resizing,” in ACM Trans. Graph., vol. 26, no. 3, 2007, p. 10.
* [19] J. Sun and H. Ling, “Scale and object aware image retargeting for thumbnail browsing,” in Proc. IEEE Int. Conf. Comput. Vis., 2011
